version: "3.7"

services:
  app:
      build: .
      ports:
        - "8081:8080"
      networks:
        - my-networks
      depends_on:
        - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aditya
      POSTGRES_DB: spring-docker
    ports:
      - "5433:5432"
    networks:
      - my-networks
    volumes:
      -  postgres-data:/var/lib/postgresql/data

networks:
  my-networks:
    driver: bridge


volumes:
  postgres-data: